/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-03-15 05:23:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/D:/new%20watches%20brand%20direct/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WatchesBrandDirect/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1482320444000L));
    _jspx_dependants.put("jar:file:/D:/new%20watches%20brand%20direct/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WatchesBrandDirect/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
    _jspx_dependants.put("/WEB-INF/Views/footer.jsp", Long.valueOf(1486624520025L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar", Long.valueOf(1488866040169L));
    _jspx_dependants.put("/WEB-INF/Views/header.jsp", Long.valueOf(1489552435472L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1487576301035L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("  <title>Bootstrap Case</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"Resources/css/header.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write(" <script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.0.1/angular.min.js\"></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-2.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("    <link href=\"https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<nav style=\"margin-top:-40px;\" class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav \">\r\n");
      out.write("        <li class=\"active\"><a href=\"home\">Home\r\n");
      out.write("        <span class=\"glyphicon glyphicon-home\"></span></a></li>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">BRANDS<span class=\"caret\"></span></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a href=\"#\">Rado</a></li>\r\n");
      out.write("            <li><a href=\"#\">Rolex</a></li>\r\n");
      out.write("            <li><a href=\"#\">GShock</a></li>\r\n");
      out.write("             <li><a href=\"#\">Fastrack</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a href=\"contactus\">ContactUs\r\n");
      out.write("        <span class=\"glyphicon glyphicon-phone\"></span></a></li>\r\n");
      out.write("         ");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("        <button style=\"margin-top:10px;\" type=\"button\" class=\"btn btn-default btn-sm\">\r\n");
      out.write("          <span class=\"glyphicon glyphicon-shopping-cart\"></span> Shopping Cart : 0\r\n");
      out.write("        </button></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </ul>\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"background-color:#fffff; class=\"jumbotron\">\r\n");
      out.write(" <div class=\"container-fluid\">\r\n");
      out.write(" <div class=\"row\">\r\n");
      out.write("      <div class=\"col-sm-4\">\r\n");
      out.write("           <a><img style= \" width:100%;height:200px;margin-top:2px;margin-left:0px;\"class=\"img-responsive\" src=\"Resources/images/banner1.jpg\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("         <div class=\"col-sm-4\">\r\n");
      out.write("         <a class=\"img-responsive\"  class=\"navbar-brand\" href=\"#\"><img style=\" width:100%;height:200px;margin-top:2px;margin-left:0px;\" id=\"banner\" src=\"Resources/images/logo.png\"></img></a>\r\n");
      out.write("        </div>\r\n");
      out.write("         <div class=\"col-sm-4\">\r\n");
      out.write("         <a class=\"img-responsive\"  class=\"navbar-brand\" href=\"#\"><img style=\" width:100%;height:200px;margin-top:2px;margin-left:0px;\" id=\"banner\" src=\"Resources/images/banner3.jpg\"></img></a>\r\n");
      out.write("        </div>\r\n");
      out.write("           \r\n");
      out.write("       \r\n");
      out.write("       </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       </div>\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".carousel-inner > .item > img,\r\n");
      out.write("  .carousel-inner > .item > a > img {\r\n");
      out.write("      width:80%;\r\n");
      out.write("      height:320;\r\n");
      out.write("      margin: auto;\r\n");
      out.write("  }\r\n");
      out.write("  #myCarousel\r\n");
      out.write("  {\r\n");
      out.write("  margin-left:-100px;\r\n");
      out.write("  \r\n");
      out.write("  margin-right:-100px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  @import url(http://fonts.googleapis.com/css?family=Anaheim);\r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  border: none;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("*:before,\r\n");
      out.write("*:after{\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1{\r\n");
      out.write("    \r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("\tmargin: 5% auto 0;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tfont-family: 'Copperplate Gothic Bold';\r\n");
      out.write("\tfont-size: 6em;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\ttext-shadow: 0 1px Black, 0 2px black;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".container{\r\n");
      out.write("\tmargin: 4% auto;\r\n");
      out.write("\twidth: 210px;\r\n");
      out.write("\theight: 140px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tperspective: 1000px;\r\n");
      out.write("}\r\n");
      out.write("#carousel{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttransform-style: preserve-3d;\r\n");
      out.write("\tanimation: rotation 20s infinite linear;\r\n");
      out.write("}\r\n");
      out.write("#carousel:hover{\r\n");
      out.write("\tanimation-play-state: paused;\r\n");
      out.write("}\r\n");
      out.write("#carousel figure{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\theight: 50%px;\r\n");
      out.write("\tleft: 10px;\r\n");
      out.write("\ttop: 10px;\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tborder: solid 5px black;\r\n");
      out.write("}\r\n");
      out.write("#carousel figure:nth-child(1){transform: rotateY(0deg) translateZ(288px);}\r\n");
      out.write("#carousel figure:nth-child(2) { transform: rotateY(40deg) translateZ(288px);}\r\n");
      out.write("#carousel figure:nth-child(3) { transform: rotateY(80deg) translateZ(288px);}\r\n");
      out.write("#carousel figure:nth-child(4) { transform: rotateY(120deg) translateZ(288px);}\r\n");
      out.write("#carousel figure:nth-child(5) { transform: rotateY(160deg) translateZ(288px);}\r\n");
      out.write("#carousel figure:nth-child(6) { transform: rotateY(200deg) translateZ(288px);}\r\n");
      out.write("#carousel figure:nth-child(7) { transform: rotateY(240deg) translateZ(288px);}\r\n");
      out.write("#carousel figure:nth-child(8) { transform: rotateY(280deg) translateZ(288px);}\r\n");
      out.write("#carousel figure:nth-child(9) { transform: rotateY(320deg) translateZ(288px);}\r\n");
      out.write("\r\n");
      out.write("#gl{\r\n");
      out.write("\t-webkit-filter: grayscale(1);\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\ttransition: all .5s ease;\r\n");
      out.write("}\r\n");
      out.write("#gl:hover{\r\n");
      out.write("\t-webkit-filter: grayscale(0);\r\n");
      out.write("  transform: scale(1.2,1.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes rotation{\r\n");
      out.write("\tfrom{\r\n");
      out.write("\t\ttransform: rotateY(0deg);\r\n");
      out.write("\t}\r\n");
      out.write("\tto{\r\n");
      out.write("\t\ttransform: rotateY(360deg);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("#carouselcontainer{      width:80%;\r\n");
      out.write("      height:320;\r\n");
      out.write("      margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-big{\r\n");
      out.write("    position: relative;\r\n");
      out.write("\tmin-height: 1px;\r\n");
      out.write("\tpadding-right: 15px;\r\n");
      out.write("\tpadding-left: 15px;\r\n");
      out.write("\twidth:20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hovereffect {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  float: left;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  cursor: default;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hovereffect .overlay {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  background-color: transparent;\r\n");
      out.write("  -webkit-transition: all 0.4s ease-in-out;\r\n");
      out.write("  transition: all 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hovereffect:hover .overlay {\r\n");
      out.write("  background-color: rgba(48, 152, 157, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hovereffect img {\r\n");
      out.write("  display: block;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hovereffect h2 {\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  color:#FFFFFF;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  font-size: 25px;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  background: rgba(0, 0, 0, 0.6);\r\n");
      out.write("  -webkit-transform: translateY(45px);\r\n");
      out.write("  -ms-transform: translateY(45px);\r\n");
      out.write("  transform: translateY(45px);\r\n");
      out.write("  -webkit-transition: all 0.4s ease-in-out;\r\n");
      out.write("  transition: all 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hovereffect:hover h2 {\r\n");
      out.write("  -webkit-transform: translateY(5px);\r\n");
      out.write("  -ms-transform: translateY(5px);\r\n");
      out.write("  transform: translateY(5px);\r\n");
      out.write("  margin:0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hovereffect p.info {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  padding: 7px 14px;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  border: 2.5px solid #FFFFFF;\r\n");
      out.write("  background-color: transparent;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  filter: alpha(opacity=0);\r\n");
      out.write("  -webkit-transform: scale(0);\r\n");
      out.write("  -ms-transform: scale(0);\r\n");
      out.write("  transform: scale(0);\r\n");
      out.write("  -webkit-transition: all 0.4s ease-in-out;\r\n");
      out.write("  transition: all 0.4s ease-in-out;\r\n");
      out.write("  font-weight: normal;\r\n");
      out.write("  margin: 7px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hovereffect:hover p.info {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("  filter: alpha(opacity=100);\r\n");
      out.write("  -webkit-transform: scale(1);\r\n");
      out.write("  -ms-transform: scale(1);\r\n");
      out.write("  transform: scale(1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hovereffect p.info:hover {\r\n");
      out.write("  box-shadow: 0 0 5px #fff;\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"Resources/css/index.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#132E49;\">\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin-top:-10px;margin-bottom:150px; height:320px;width:80%;\" class=\"container\" >\r\n");
      out.write("  <br>\r\n");
      out.write("  <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("    <!-- Indicators -->\r\n");
      out.write("    <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("    </ol>\r\n");
      out.write("\r\n");
      out.write("    <!-- Wrapper for slides -->\r\n");
      out.write("    <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("      <div class=\"item active\">\r\n");
      out.write("        <img src=\"Resources/images/carousal1.jpg\" alt=\"Chania\" width=\"460\" height=\"345\">\r\n");
      out.write("       <div class=\"carousel-caption\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"Resources/images/carousal2.jpg\" alt=\"Chania\" width=\"460\" height=\"345\">\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"Resources/images/carousal3.jpg\" alt=\"Flower\" width=\"460\" height=\"345\">\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"Resources/images/carousal4.jpg\" alt=\"Flower\" width=\"460\" height=\"345\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Left and right controls -->\r\n");
      out.write("    <a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Previous</span>\r\n");
      out.write("    </a>\r\n");
      out.write("   <a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Next</span>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"background-color:#10273E; class=\"jumbotron\">\r\n");
      out.write(" <div class=\"container-fluid\">\r\n");
      out.write(" <div class=\"row\">\r\n");
      out.write("      <div class=\"col-sm-4\">\r\n");
      out.write("          <div class=\"hovereffect\">\r\n");
      out.write("            <img style= \" width:100%;height:200px;margin-top:20px;margin-left:0px;\" class=\"img-responsive\" src=\"Resources/images/casual.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"overlay\">\r\n");
      out.write("               <h2>CASUAL</h2>\r\n");
      out.write("               <p class=\"info\">\r\n");
      out.write("               <a href=\"#\" style=\"color:#FFFFFF; font-size:15px;font-family:Arial Black \">SHOP NOW</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"col-sm-4\">\r\n");
      out.write("          <div class=\"hovereffect\">\r\n");
      out.write("           <img style= \" width:100%;height:200px;margin-top:20px;margin-left:0px;\" class=\"img-responsive\" src=\"Resources/images/luxury.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"overlay\">\r\n");
      out.write("               <h2>LUXURY</h2>\r\n");
      out.write("               <p class=\"info\">\r\n");
      out.write("               <a href=\"#\"style=\"color:#FFFFFF;  font-size:15px; font-family:Arial Black\">SHOP NOW</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("           </div>\r\n");
      out.write("           </div>\r\n");
      out.write("          <div class=\"col-sm-4\">\r\n");
      out.write("           <div class=\"hovereffect\">\r\n");
      out.write("            <img style= \" width:100%;height:200px;margin-top:20px;margin-left:0px;\" class=\"img-responsive\" src=\"Resources/images/sports.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"overlay\">\r\n");
      out.write("               <h2>Sports</h2>\r\n");
      out.write("               <p class=\"info\">\r\n");
      out.write("               <a href=\"#\" style=\"color:#FFFFFF;  font-size:15px; font-family:Arial Black\"> SHOP NOW</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("   <h1 style=\"color:#FDE08E;\">LUXURY BRANDS</h1>\r\n");
      out.write("   \r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    \t<div id=\"carousel\">\r\n");
      out.write("\t\t\t<figure><img id=\"gl\"style=\"width:100%;height:200px;margin-top:20px;margin-left:0px;hover\"class=\"img-responsive\" src=\"Resources/images/Rolex.png\" alt=\"\"></figure>\r\n");
      out.write("\t\t\t<figure><img id=\"gl\"style=\"width:100%;height:200px;margin-top:20px;margin-left:0px;hover\"class=\"img-responsive\" src=\"Resources/images/Rado1.jpg\" alt=\"\"></figure>\r\n");
      out.write("\t\t\t<figure><img id=\"gl\"style=\"width:100%;height:200px;margin-top:20px;margin-left:0px;hover\"class=\"img-responsive\" src=\"Resources/images/Omega.jpg\" alt=\"\"></figure>\r\n");
      out.write("\t\t\t<figure><img id=\"gl\"style=\"width:100%;height:200px;margin-top:20px;margin-left:0px;hover\"class=\"img-responsive\" src=\"Resources/images/gucci.jpg\" alt=\"\"></figure>\r\n");
      out.write("\t        <figure><img id=\"gl\"style=\"width:100%;height:200px;margin-top:20px;margin-left:0px;hover\"class=\"img-responsive\" src=\"Resources/images/cartier.jpg\" alt=\"\"></figure>\r\n");
      out.write("\t\t    <figure><img id=\"gl\"style=\"width:100%;height:200px;margin-top:20px;margin-left:0px;hover\"class=\"img-responsive\" src=\"Resources/images/hublot.jpg\" alt=\"\"></figure>\r\n");
      out.write("\t\t      <figure><img id=\"gl\"style=\"width:100%;height:200px;margin-top:20px;margin-left:0px;hover\"class=\"img-responsive\" src=\"Resources/images/pp1.jpg\" alt=\"\"></figure>\r\n");
      out.write("\t\t      <figure><img id=\"gl\"style=\"width:100%;height:200px;margin-top:20px;margin-left:0px;hover\"class=\"img-responsive\" src=\"Resources/images/ap1.jpg\" alt=\"\"></figure>\r\n");
      out.write("\t\t      <figure><img id=\"gl\"style=\"width:100%;height:200px;margin-top:20px;margin-left:0px;hover\"class=\"img-responsive\" src=\"Resources/images/piaget.png\" alt=\"\"></figure>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/footer.css\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("  <footer class=\"footer-bs\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        \t<div class=\"col-md-3 footer-brand animated fadeInLeft\">\r\n");
      out.write("            \t<h2>Watch Brands Direct</h2>\r\n");
      out.write("                <p></p>\r\n");
      out.write("                <p>Â© 2017, All rights reserved</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-4 footer-nav animated fadeInUp\">\r\n");
      out.write("            \t<h4>Menu â</h4>\r\n");
      out.write("            \t<div class=\"col-md-6\">\r\n");
      out.write("                    <ul class=\"pages\">\r\n");
      out.write("                        <li><a href=\"#\">Travel</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Nature</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Explores</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Science</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Advice</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            \t<div class=\"col-md-6\">\r\n");
      out.write("                    <ul class=\"list\">\r\n");
      out.write("                        <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Contacts</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Terms & Condition</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-2 footer-social animated fadeInDown\">\r\n");
      out.write("            \t<h4>Follow Us</h4>\r\n");
      out.write("            \t<ul>\r\n");
      out.write("                \t<li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("                \t<li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("                \t<li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("                \t<li><a href=\"#\"></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-3 footer-ns animated fadeInRight\">\r\n");
      out.write("            \t<h4>Newsletter</h4>\r\n");
      out.write("                <p>A rover wearing a fuzzy suit doesnât alarm the real penguins</p>\r\n");
      out.write("                <p>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" placeholder=\"Search for...\">\r\n");
      out.write("                      <span class=\"input-group-btn\">\r\n");
      out.write("                        <button class=\"btn btn-default\" type=\"button\"><span class=\"glyphicon glyphicon-envelope\"></span></button>\r\n");
      out.write("                      </span>\r\n");
      out.write("                    </div><!-- /input-group -->\r\n");
      out.write("                 </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <section style=\"text-align:center; margin:10px auto;\"><p>Designed by <a href=\"http://enfoplus.net\">Ritika Khurana</a></p></section>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/Views/header.jsp(50,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setVar("url");
    // /WEB-INF/Views/header.jsp(50,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/admin/product/productform");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/Views/header.jsp(51,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      ");
        if (_jspx_meth_security_005fauthorize_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("   \r\n");
        out.write("   ");
        if (_jspx_meth_c_005furl_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("   \r\n");
        out.write("   <li><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${allProducts}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">Browse all products</a></li>\r\n");
        out.write("    <li class=\"dropdown\">\r\n");
        out.write("\t\t\t<a href=\"\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
        out.write("                     Select by Category<b class=\"caret\"></b></a>\r\n");
        out.write("\t\t\t<ul class=\"dropdown-menu\">\r\n");
        out.write("\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t</ul>\r\n");
        out.write("\t\t\t</li>\r\n");
        out.write(" ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_security_005fauthorize_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_security_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    _jspx_th_security_005fauthorize_005f0.setPageContext(_jspx_page_context);
    _jspx_th_security_005fauthorize_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/Views/header.jsp(52,6) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_security_005fauthorize_005f0.setAccess("hasRole('ROLE_ADMIN')");
    int _jspx_eval_security_005fauthorize_005f0 = _jspx_th_security_005fauthorize_005f0.doStartTag();
    if (_jspx_eval_security_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write("\r\n");
      out.write("   <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Add New Product</a></li>\r\n");
      out.write("   ");
    }
    if (_jspx_th_security_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.reuse(_jspx_th_security_005fauthorize_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.reuse(_jspx_th_security_005fauthorize_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/Views/header.jsp(56,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setVar("allProducts");
    // /WEB-INF/Views/header.jsp(56,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/all/product/getAllProducts");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/Views/header.jsp(63,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("c");
    // /WEB-INF/Views/header.jsp(63,3) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categories }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<li>\r\n");
          out.write("<a href=\"");
          if (_jspx_meth_c_005furl_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\" >\r\n");
          out.write("  ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.categoryDetails }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/Views/header.jsp(65,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/all/product/productsByCategory?searchCondition=${c.categoryDetails }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/Views/header.jsp(74,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("     \r\n");
        out.write("\t\t\t<li><a href=\"\">welcome ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</a></li>\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /WEB-INF/Views/header.jsp(78,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name ==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t<li><a href=\"");
        if (_jspx_meth_c_005furl_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\"><span class=\"glyphicon glyphicon-log-in\"></span>  Login</a></li>\r\n");
        out.write("\t\t\t<li> <a href=\"");
        if (_jspx_meth_c_005furl_005f4(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\"><span class=\"glyphicon glyphicon-pencil\"></span> Register</a></li>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /WEB-INF/Views/header.jsp(79,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/login");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /WEB-INF/Views/header.jsp(80,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/register");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /WEB-INF/Views/header.jsp(83,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t<li><a href=\"");
        if (_jspx_meth_c_005furl_005f5(_jspx_th_c_005fif_005f3, _jspx_page_context))
          return true;
        out.write("\">logout</a></li>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
    // /WEB-INF/Views/header.jsp(84,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/j_spring_security_logout");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }
}
